config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: "custom/sessions", registrations: "custom/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root 'categories#index'
    resources :users
    resources :categories
    resources :taxes
    resources :products
  end
  
  root 'products#index'
  
  get 'checkout/cart', to: 'checkout#cart'
  get 'checkout/product/:product_id', to: 'checkout#product'
  get 'checkout/complete', to: 'checkout#complete'
  post 'checkout/complete', to: 'checkout#request_twof_authentication'
  post 'checkout/verify_payment', to: 'checkout#verify_authentication'
  
  get 'orders', to: 'orders#index'
  get 'orders/:id', to: 'orders#show'
  get 'orders/:id/resend_order_conformation', to: 'orders#resend_order_conformation'
  
  post 'add_to_cart', to: 'carts#add'
  post 'remove_from_cart', to: 'carts#remove'
end

app/models/tax.rb
class Tax < ApplicationRecord
  has_many :payment_token_taxes
  
  scope :active, -> {where(status: true)}
  
  # model validations
  validates_presence_of :name, :amount, :tax_type
  validate :tax_type_validation
  
  def detailed_name
    return "#{name}@#{amount}%" if tax_type.downcase == "percent"
    return name
  end

  private

  # validate tax type to either percent of amount
  def tax_type_validation
    errors.add(:tax_type, "Please choose one from given options") unless ["amount", "percent"].include? tax_type
  end
end

app/controllers/admin/taxes_controller.rb
class Admin::TaxesController < Admin::BaseController
  # before actions
  before_action :find_tax, only: [:edit, :update, :destroy]
  
  # get all the taxes list
  def index
    @taxes = Tax.all
  end
  
  # new tax form render
  def new
    @tax = Tax.new
  end
  
  # tax edit form render
  def edit
  end
  
  # tax creation and handling failure
  def create
    @tax = Tax.new(tax_params)
    if @tax.save
      redirect_to admin_taxes_path
        flash[:success] = "Woohoo! tax created successfully."
    else
      render 'new'
      flash[:error] = "Oops! Something went wrong!"
    end
  end
  
  # tax updation and handling failure
  def update
    if @tax.update(tax_params)
      redirect_to admin_taxes_path
        flash[:success] = "Woohoo! tax updated successfully."
    else
      render 'edit'
      flash[:error] = "Oops! Something went wrong!"
    end
  end
  
  # destory the tax
  def destroy
    @tax.destroy
    redirect_to admin_taxes_path
  end
  
  private
  
  # get the tax form params
  def find_tax
    @tax = Tax.find_by(id: params[:id])
  end
  
  # tax permit params
  def tax_params
    params.require(:tax).permit(:name, :tax_type, :status, :amount)
  end
end
  

app/views/admin/taxes/_form.html.haml
= form_for [:admin, @tax], :html => {class: 'category-form'} do |f|
  .row
    .col-md-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :tax_type
        - tax_options = [["Percent","percent"], ["Amount","amount"]]
        .dropdown
          = f.select :tax_type, tax_options,  :html => {class: 'btn btn-default dropdown-toggle', type: 'button'}
      .form-group
        = f.label :status
        - options = [["Active",true], ["In Active",false]]
        .dropdown
          = f.select :status, options,  :html => {class: 'btn btn-default dropdown-toggle', type: 'button'}
      .form-group
        = f.label :amount
        = f.text_field :amount, class: 'form-control'
      .form-group
        = f.submit 'submit', {class: 'btn btn-primary float-right'}

app/views/admin/taxes/edit.html.haml
%h2
  Edit - 
  = @tax.name
= render 'form'

app/views/admin/taxes/index.html.haml
%h1
  Taxes
= link_to '+ Add Tax', new_admin_tax_path, {class: 'btn btn-success float-right', id: 'add-product-button'}
%table.table
  %thead.thead-dark
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} Name
      %th{:scope => "col"} Tax Type
      %th{:scope => "col"} Amount
      %th{:scope => "col"} Status
      %th{:scope => "col"} Actions
  %tbody
    - @taxes.each do |tax|
      %tr
        %td #{tax.id}
        %td #{tax.name}
        %td #{tax.tax_type}
        %td #{tax.amount}
        %td #{tax.status}
        %td 
          = link_to('', edit_admin_tax_path(tax), {class: 'btn btn-primary fa fa-pencil'}) |
          = link_to('', admin_tax_path(tax), method: :delete,
                data: { confirm: 'Are you certain you want to delete this?' }, 
                class: 'btn btn-danger fa fa-trash')

app/views/admin/taxes/new.html.haml
%h2
  Add new Tax
= render 'form'