config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: "custom/sessions", registrations: "custom/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root 'categories#index'
    resources :users
    resources :categories
    resources :taxes
    resources :products
  end
  
  root 'products#index'
  
  get 'checkout/cart', to: 'checkout#cart'
  get 'checkout/product/:product_id', to: 'checkout#product'
  get 'checkout/complete', to: 'checkout#complete'
  post 'checkout/complete', to: 'checkout#request_twof_authentication'
  post 'checkout/verify_payment', to: 'checkout#verify_authentication'
  
  get 'orders', to: 'orders#index'
  get 'orders/:id', to: 'orders#show'
  get 'orders/:id/resend_order_conformation', to: 'orders#resend_order_conformation'
  
  post 'add_to_cart', to: 'carts#add'
  post 'remove_from_cart', to: 'carts#remove'
end

app/models/category.rb
class Category < ApplicationRecord
  # model assocations
  belongs_to :user, class_name: "User", foreign_key: "created_by", optional: true
  has_many :products, dependent: :destroy

  # model validations
  validates :name, presence: true
  # validates :created_by, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
# before actions
before_action :find_category, only: [:edit, :show, :update, :destroy]

# get all the categories list
def index
  @categories = Category.all.order(:created_at)
end

# display category details
def show
end

# new category form render
def new
  @category = Category.new
end

# category edit form render
def edit
end

# category creation and handling failure
def create
  @category = Category.new(category_params)
  if @category.save
    redirect_to admin_categories_path
      flash[:success] = "Woohoo! category created successfully."
  else
    render 'new'
    flash[:error] = "Oops! Something went wrong!"
  end
end

# category updation and handling failure
def update
  if @category.update(category_params)
    redirect_to admin_categories_path
      flash[:success] = "Woohoo! category updated successfully."
  else
    render 'edit'
    flash[:error] = "Oops! Something went wrong!"
  end
end

# destory the category
def destroy
  @category.destroy
  redirect_to admin_categories_path
end

private

# get the category form params
def find_category
  @category = Category.find_by(id: params[:id])
end

# category permit params
def category_params
  params.require(:category).permit(:name, :created_by, :updated_by)
end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.haml
= form_for [:admin, @category], :html => {class: 'category-form'} do |f|
  .row
    .col-md-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.hidden_field :created_by, value: current_user.id
        = f.hidden_field :updated_by, value: current_user.id
        = f.submit 'submit', {class: 'btn btn-primary float-right'}

app/views/admin/categories/edit.html.haml
%h2
  Edit - 
  = @category.name
= render 'form'

app/views/admin/categories/index.html.haml
%h1
  Categories
= link_to '+ Add Category', new_admin_category_path, {class: 'btn btn-success float-right', id: 'add-product-button'}
%table.table
  %thead.thead-dark
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} Name
      %th{:scope => "col"} Created By
      %th{:scope => "col"} Actions
  %tbody
    - @categories.each do |category|
      %tr
        %td #{category.id}
        %td 
          = link_to(category.name, admin_category_path(category)) 
        %td #{User.find(category.created_by).first_name}
        %td 
          = link_to('', edit_admin_category_path(category), {class: 'btn btn-primary fa fa-pencil'}) |
          = link_to('', admin_category_path(category), method: :delete,
                data: { confirm: 'Are you certain you want to delete this?' }, 
                class: 'btn btn-danger fa fa-trash')

app/views/admin/categories/new.html.haml
%h2
  Add new Category
= render 'form'

app/views/admin/categories/show.html.haml
%h2
  #{@category.name} - Products

%table.table
  %thead.thead-dark
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} Name
      %th{:scope => "col"} Category
      %th{:scope => "col"} Price
      %th{:scope => "col"} Offer Price
      %th{:scope => "col"} Actions
  %tbody
    - @category.products.each do |product|
      %tr
        %td #{product.id}
        %td 
          = link_to(product.name, admin_product_path(product)) 
        %td #{product.category.name}
        %td #{product.price}
        %td #{product.offer_price}
        %td 
          = link_to('', edit_admin_product_path(product), {class: 'btn btn-primary fa fa-pencil'}) |
          = link_to('', admin_product_path(product), method: :delete,
              data: { confirm: 'Are you certain you want to delete this?' }, 
              class: 'btn btn-danger fa fa-trash')