config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: "custom/sessions", registrations: "custom/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root 'categories#index'
    resources :users
    resources :categories
    resources :taxes
    resources :products
  end
  
  root 'products#index'
  
  get 'checkout/cart', to: 'checkout#cart'
  get 'checkout/product/:product_id', to: 'checkout#product'
  get 'checkout/complete', to: 'checkout#complete'
  post 'checkout/complete', to: 'checkout#request_twof_authentication'
  post 'checkout/verify_payment', to: 'checkout#verify_authentication'
  
  get 'orders', to: 'orders#index'
  get 'orders/:id', to: 'orders#show'
  get 'orders/:id/resend_order_conformation', to: 'orders#resend_order_conformation'
  
  post 'add_to_cart', to: 'carts#add'
  post 'remove_from_cart', to: 'carts#remove'
end

app/models/product.rb
class Product < ApplicationRecord
  # model associations
  has_many :cart_items
  
  belongs_to :user, class_name: "User", foreign_key: "created_by", optional: true
  belongs_to :category

  # model validations
  validates_presence_of :name, :category_id, :price

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

# before actions
before_action :find_product, only: [:edit, :show, :update, :destroy]

  # get all the products list
  def index
    @products = Product.all
  end

  # display product details
  def show
  end
  
  # new product form render
  def new
    @product = Product.new
  end

  # product edit form render
  def edit
  end

  # product creation and handling failure
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
      flash[:success] = "Woohoo! product created successfully."
    else
      render 'new'
      flash[:error] = "Oops! Something went wrong!"
    end
  end

  # product updation and handling failure
  def update
    if @product.update(product_params)
      redirect_to admin_products_path
      flash[:success] = "Woohoo! product updated successfully."
    else
      render 'edit'
      flash[:error] = "Oops! Something went wrong!"
    end
  end

  # destory the product
  def destroy
    @product.destroy
    redirect_to admin_products_path
  end

  private

  # get the product form params
  def find_product
    @product = Product.find_by(id: params[:id])
  end

  # product permit params
  def product_params
    params.require(:product).permit(:name, :description, :category_id, :price, :offer_price, :status, :created_by)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # before actions
  before_action :find_product, only: [:show]

  # get all the products list
  def index
    @products = Product.all
  end

  # display product details
  def show
  end
  
  private

  # get the product form params
  def find_product
    @product = Product.find_by(id: params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def fetch_product_img
    img_arr = ["https://images-eu.ssl-images-amazon.com/images/I/51bwFsBc0TL._SY346_.jpg", 
      "https://images-na.ssl-images-amazon.com/images/I/61zR1dZFrzL._SL1500_.jpg", 
      "https://m.media-amazon.com/images/I/71X1ipYOLbL._AC_UY436_FMwebp_QL70_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71yVflZyOYL._SL1500_.jpg"
    ]

    return img_arr.sample
  end
end

app/views/admin/products/_form.html.haml
= form_for [:admin, @product], :html => {class: 'product-form'} do |f|
  .row
    .col-md-6
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'
      .row
        .col-md-6
          .form-group
            = f.label :category
            - options = options_from_collection_for_select(Category.all, 'id', 'name')
            = f.select :category_id,  options, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :status
            - options = [["Active",1], ["InActive",0]]
            = f.select :status,  options, class: 'form-control'
      .row
        .col-md-6
          .form-group
            = f.label :price
            = f.number_field :price, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :offer_price
            = f.number_field :offer_price, class: 'form-control'
      .form-group
        = f.hidden_field :created_by, value: 1
        = f.submit 'submit', {class: 'btn btn-primary float-right'}
      

app/views/admin/products/edit.html.haml
%h2
  Edit - 
  = @product.name
= render 'form'

app/views/admin/products/index.html.haml
.container  
  %h1
    Products
  = link_to '+ Add Products', new_admin_product_path, {class: 'btn btn-success float-right', id: 'add-product-button'}
  %table.table
    %thead.thead-dark
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} Name
        %th{:scope => "col"} Category
        %th{:scope => "col"} Price
        %th{:scope => "col"} Offer Price
        %th{:scope => "col"} Actions
    %tbody
      - @products.each do |product|
        %tr
          %td #{product.id}
          %td 
            = link_to(product.name, admin_product_path(product)) 
          %td #{product.category.name}
          %td #{product.price}
          %td #{product.offer_price}
          %td 
            = link_to('', edit_admin_product_path(product), {class: 'btn btn-primary fa fa-pencil'}) |
            = link_to('', admin_product_path(product), method: :delete,
                data: { confirm: 'Are you certain you want to delete this?' }, 
                class: 'btn btn-danger fa fa-trash')

app/views/admin/products/new.html.haml
%h2
  Add new Product
= render 'form'